# Generated by Django 5.2.3 on 2025-07-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True,
                help_text="URL для оплаты через Stripe",
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("succeeded", "Успешно оплачен"),
                    ("failed", "Ошибка оплаты"),
                ],
                default="pending",
                help_text="Статус платежа (ожидает, успешно, ошибка)",
                max_length=20,
                verbose_name="Статус платежа",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор платежа в системе Stripe",
                max_length=255,
                null=True,
                verbose_name="ID платежа Stripe",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счет"),
                    ("make_qr_code", "Перевод по QR-коду"),
                    ("stripe", "Stripe"),
                ],
                help_text="Способ оплаты",
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
