# Generated by Django 5.2.3 on 2025-07-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment_payment_url_payment_status_payment_stripe_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счет"),
                    ("make_qr_code", "Перевод по QR-коду"),
                    ("stripe", "Stripe"),
                    ("free", "Бесплатно"),
                ],
                help_text="Способ оплаты",
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
