version: '3.10'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - web

  redis:
    image: redis:8.2.1
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./deploy/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web

  backend:
    build: .
    restart: always
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=skillshare_platform.settings
    volumes:
      - static_volume:/vol/static
      - media_volume:/vol/media
    depends_on:
      - db
      - redis
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery_worker:
    build: .
    command: celery -A skillshare_platform worker -l info -E -Q default
    restart: always
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - backend
    networks:
      - web

  celery_beat:
    build: .
    command: celery -A skillshare_platform beat -l info
    restart: always
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - backend
    networks:
      - web

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/vol/static:ro
      - media_volume:/vol/media:ro
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:

networks:
  web:
    driver: bridge
