name: Django CI/CD

on:
  push:
    branches:
      - main # Или develop, если вы используете develop в качестве основной ветки

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Deploy to production
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/SkillShare # Путь к вашему проекту на сервере
            git pull origin main # Или develop, если вы используете develop
            source .venv/bin/activate # Или путь к вашему виртуальному окружению
            pip install -r requirements.txt
            python manage.py collectstatic --noinput
            python manage.py migrate
            sudo systemctl restart gunicorn # Используйте systemctl или supervisor, в зависимости от вашей настройки
            sudo systemctl restart nginx