# Generated by Django 5.2.3 on 2025-06-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_user",
        ),
    ]
