# Generated by Django 5.2.3 on 2025-07-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="fixed_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Укажите фиксированную стоимость курса. Если пусто, стоимость будет рассчитана по урокам.",
                max_digits=10,
                null=True,
                verbose_name="Фиксированная стоимость",
            ),
        ),
    ]
