# Generated by Django 5.2.3 on 2025-07-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_fixed_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Время последнего обновления курса. Используется для контроля частоты уведомлений.",
                null=True,
                verbose_name="Дата последнего обновления курса",
            ),
        ),
    ]
