name: CI & Deploy

on:
  push:
    branches:
      - develop
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_and_tests:
    name: Lint and Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: skillshare_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_NAME: skillshare_test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linters and format checks
        run: |
          flake8
          isort --check-only --profile black .
          black --check .

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

  build_images:
    name: Build Docker images (check)
    runs-on: ubuntu-latest
    needs: lint_and_tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image (check)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: linux/amd64

  deploy:
    name: Deploy to remote server
    runs-on: ubuntu-latest
    needs:
      - lint_and_tests
      - build_images
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            # branch name passed from workflow
            export GITHUB_REF_NAME="${{ github.ref_name }}"
            export DEPLOY_PATH=${{ secrets.DEPLOY_PATH }}
            echo "Deploying branch $GITHUB_REF_NAME to $DEPLOY_PATH"
            if [ ! -d "$DEPLOY_PATH" ]; then
              mkdir -p "$DEPLOY_PATH"
              git clone https://github.com/${{ github.repository }} "$DEPLOY_PATH"
            fi
            cd "$DEPLOY_PATH"
            git fetch --all
            git checkout "$GITHUB_REF_NAME" || git checkout -B "$GITHUB_REF_NAME" origin/"$GITHUB_REF_NAME"
            git reset --hard origin/"$GITHUB_REF_NAME"
            # ensure .env exists
            if [ ! -f .env ]; then
              echo ".env not found in $DEPLOY_PATH. Please create it from .env.example and add production values." >&2
              exit 1
            fi
            # Build & run with Docker Compose
            docker compose -f docker-compose.prod.yml pull || true
            docker compose -f docker-compose.prod.yml up -d --build --remove-orphans
            # Run migrations and collectstatic in backend
            docker compose -f docker-compose.prod.yml exec -T backend python manage.py migrate --noinput || true
            docker compose -f docker-compose.prod.yml exec -T backend python manage.py collectstatic --noinput || true
            docker image prune -f || true
